### ISSUE TITLE
jQuery Conflicts

### ISSUE THREAD

**Issue by Shifrin** [froala/yii2-froala-editor#3]
Hi,

Thank you for this extension.

I have found some serious js errors when I try to integrate the extension in my project. The following errors appear in Firebug console in Firefox. But in Chrome, it's just working, but not overriding the `clientOptions` when specified and no errors are showing in the console.

```js
TypeError: a.FE is undefined
http://localhost/arabphotostore/public/assets/f79c4d17/jquery.js line 343 > eval
Line 7
TypeError: $(...).froalaEditor is not a function
http://localhost/arabphotostore/public/assets/f79c4d17/jquery.js line 343 > eval
Line 1
```

I guessed the problem due to the jQuery conflicts. When I try to comment the following lines in `FroalaEditorWidget` it's just working fine.

```php
// $this->updateAsset(); line 69
// $view ->registerJsFile('http://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js'); line 70
```

I think you better add the following for the jQuery in `FroalaEditorAsset`.

```php
public $depends = [
        'yii\web\YiiAsset',
];
```

You may add a property like `enableFontAwesomeCSS` in `FroalaEditorWidget`, so it will help to enable `font-awesome.min.css` only on demand and avoid 2 times include.

**Comment by dungphanxuan** [comment]
@Shifrin , Froala work default with Jquery 1.1. So i replace jquery 2.0( Yii2 default) by jquery 1.1. 
@stefanneculai , do you have solution for work with jquery 2.0

**Comment by stefanneculai** [comment]
@dungphanxuan Editor works with jQuery 1.1.10+. There shouldn't be any problem with jQuery 2.0.

**Comment by dungphanxuan** [comment]
#4 fixed, you can run `composer update ` to update feature.
